# Generated by Django 2.2.5 on 2021-06-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcandidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attitude',
            name='attitude',
            field=models.CharField(choices=[('active_listening', 'Active Listening'), ('genuine', 'Genuine'), ('optimistic', 'Optimistic'), ('responsive', 'Responsive'), ('humility', 'Humility'), ('attentive', 'Attentive'), ('honest', 'Honest'), ('laidback', 'Laidback'), ('boastful', 'Boastful'), ('unsure', 'Unsure'), ('brash', 'Brash'), ('disinterested', 'Disinterested'), ('manipulative', 'Manipulative'), ('informal', 'Informal')], max_length=50, unique=True),
        ),
    ]
