# Generated by Django 2.2.5 on 2021-06-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcandidate', '0002_auto_20210621_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('sales', 'Sales'), ('human_resources', 'Human Resources'), ('marketing', 'Marketing'), ('sales_and_marketing', 'Sales & Marketing'), ('graphic_designer', 'Graphic Designer'), ('operations', 'Operations'), ('content_writer', 'Content Writer'), ('digital_marketing', 'Digital Marketing'), ('python_developer', 'Python Developer'), ('android_developer', 'Android Developer'), ('web_developer', 'Web Developer'), ('administration', 'Administration'), ('relationship_manager', 'Relationship Manager'), ('marketing_communication', 'Marketing Communication'), ('finance', 'Finance'), ('other', 'Other')], max_length=50, unique=True),
        ),
    ]
