# Generated by Django 2.2.5 on 2021-06-22 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addcandidate', '0003_auto_20210621_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('intern', 'Intern'), ('executive', 'Executive'), ('other', 'Other')], max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='recruitment',
            name='first_param_val',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=50),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='fourth_param_val',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=50),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='second_param_val',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=50),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='third_param_val',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addcandidate.Position'),
        ),
    ]
