# Generated by Django 2.2.5 on 2021-06-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcandidate', '0004_auto_20210622_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='other_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='other_role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='other_source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='position',
            field=models.CharField(choices=[('intern', 'Intern'), ('executive', 'Executive'), ('other', 'Other')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
