# Generated by Django 2.2.5 on 2021-06-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcandidate', '0006_auto_20210622_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='linkedin_link',
            field=models.URLField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='resume',
            field=models.FileField(blank=True, upload_to='resume/'),
        ),
    ]
