# Generated by Django 2.2.5 on 2021-06-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcandidate', '0007_auto_20210622_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
