# Generated by Django 2.2.5 on 2021-06-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcandidate', '0009_auto_20210624_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='first_param_val',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='fourth_param_val',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='second_param_val',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='third_param_val',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50),
        ),
    ]
