# Generated by Django 2.2.5 on 2021-06-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcandidate', '0010_auto_20210624_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
    ]
