# Generated by Django 2.2.5 on 2021-06-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcandidate', '0011_auto_20210624_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='first_meeting_status',
            field=models.CharField(choices=[('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('meeting_to_be_held', 'Meeting To Be Held')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='interview_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='interview_time',
            field=models.TimeField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='second_meeting_status',
            field=models.CharField(blank=True, choices=[('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('meeting_to_be_held', 'Meeting To Be Held')], max_length=50, null=True),
        ),
    ]
