# Generated by Django 2.2.5 on 2021-06-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcandidate', '0013_auto_20210625_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
