# Generated by Django 2.2.5 on 2021-06-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcandidate', '0015_recruitment_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_interview_date', models.DateField(blank=True, default=None, null=True)),
                ('extra_interview_time', models.TimeField(blank=True, default=None, null=True)),
                ('extra_meeting_status', models.CharField(blank=True, choices=[('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('meeting_to_be_held', 'Meeting To Be Held')], max_length=50, null=True)),
                ('additional_notes_on_extra_meeting', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='recruitment',
            name='more_meetings',
            field=models.ManyToManyField(blank=True, to='addcandidate.ExtraMeeting'),
        ),
    ]
